CREATE DATABASE PM_Ban_Laptop
GO

USE PM_Ban_Laptop
GO

CREATE TABLE NhanVien(
	MaNV VARCHAR(20) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	SoDienThoai VARCHAR(13) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Hinh VARCHAR(255) NOT NULL,
	DiaChi NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE TaiKhoan(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) ON DELETE CASCADE ON UPDATE CASCADE UNIQUE NOT NULL,
	TenDangNhap VARCHAR(100) NOT NULL,
	MatKhau VARCHAR(100) NOT NULL,
	VaiTro BIT NOT NULL
)
GO

CREATE TABLE PhieuGiamGia(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaPG VARCHAR(20) UNIQUE NOT NULL,
	TenPhieu NVARCHAR(30) NOT NULL,
	Han DATE NOT NULL,
	SoLuong INT NOT NULL,
	GiaGiam FLOAT NOT NULL,
	DieuKienHoaDon FLOAT NOT NULL
)
GO

CREATE TABLE KhachHang(
	MaKH VARCHAR(20) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	SoDienThoai VARCHAR(13) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	Email VARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE Hang(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaHang VARCHAR(20) UNIQUE NOT NULL,
	TenHang VARCHAR(50) NOT NULL,
	HoTro VARCHAR(255) NULL --link page Hãng
)
GO

CREATE TABLE DongLaptop(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaDong VARCHAR(20) UNIQUE NOT NULL,
	Hang INT FOREIGN KEY REFERENCES Hang(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	TenDong NVARCHAR(30) NOT NULL
)
GO 

CREATE TABLE PhanLoai(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaLoai VARCHAR(20) UNIQUE NOT NULL,
	TenLoai NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(255) NULL 
)
GO

CREATE TABLE RAM(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaRAM VARCHAR(20) UNIQUE NOT NULL,
	LoaiRAM VARCHAR(50) NOT NULL,
	DungLuong INT NOT NULL, --ĐV: GB
	TocDoRAM INT NOT NULL, --ĐV: MHz
	SoKheCamRoi INT NOT NULL,
	SoKheRAMConLai INT NOT NULL,
	SoRAMOnboard INT NOT NULL,
	HoTroRAMToiDa INT NOT NULL --ĐV: GB
)
GO

CREATE TABLE CPU(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaCPU VARCHAR(20) UNIQUE NOT NULL,
	HangCPU VARCHAR(20) NOT NULL,
	CongNghe VARCHAR(20) NOT NULL,
	LoaiCPU VARCHAR(20) NOT NULL,
	TocDoCPU FLOAT NOT NULL, --ĐV: GHz
	TocDoToiDa FLOAT NOT NULL, --ĐV: GHz
	SoNhan INT NOT NULL,
	SoLuong INT NOT NULL, --Số luồng
	BoNhoDem INT NOT NULL --ĐV: MB
)
GO

CREATE TABLE ManHinh(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaManHinh VARCHAR(20) UNIQUE NOT NULL,
	KichThuocManHinh FLOAT NOT NULL, --ĐV: inch
	CongNgheManHinh VARCHAR(100) NOT NULL,
	DoPhanGiai VARCHAR(30) NOT NULL, --ĐV: Pixels
	TanSoQuet INT NOT NULL,
	TamNen VARCHAR(30) NOT NULL,
	DoSang INT NOT NULL, --ĐV: nits
	DoPhuMau VARCHAR(50) NOT NULL,
	TiLemanHinh VARCHAR(30) NOT NULL,
)
GO

CREATE TABLE GPU(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaGPU VARCHAR(20) UNIQUE NOT NULL,
	LoaiCard VARCHAR(30) NOT NULL,
	Hang VARCHAR(30) NOT NULL
)
GO

CREATE TABLE OCung(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaOCung VARCHAR(20) UNIQUE NOT NULL,
	KieuOCung VARCHAR(10) NOT NULL,
	DungLuong INT NOT NULL
)
GO

CREATE TABLE HeDieuHanh(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaHeDieuHanh VARCHAR(20) UNIQUE NOT NULL,
	OS VARCHAR(30) NOT NULL,
	Versions VARCHAR(30) NOT NULL,
	Kieu INT NOT NULL --ĐV: bit
)
GO

CREATE TABLE Laptop(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaLaptop VARCHAR(20) UNIQUE NOT NULL,
	TenLaptop NVARCHAR(255) NOT NULL,
	PhanLoai INT FOREIGN KEY REFERENCES dbo.PhanLoai(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	DongLaptop INT FOREIGN KEY REFERENCES DongLaptop(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	NamSanXuat INT NOT NULL
)
GO

CREATE TABLE MoTa(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaLaptop INT FOREIGN KEY REFERENCES Laptop(ID) ON DELETE CASCADE ON UPDATE CASCADE UNIQUE NOT NULL,
	SoLuongLoa INT NOT NULL,
	Keyboard NVARCHAR(50) NOT NULL,
	TouchPad NVARCHAR(50) NOT NULL,
	CongKetNoi NVARCHAR(100) NOT NULL,
	Wifi NVARCHAR(50) NOT NULL,
	Bluetooth NVARCHAR(50) NOT NULL,
	Webcam NVARCHAR(50) NOT NULL,
	SoLuongQuat INT NOT NULL,
	TrongLuong FLOAT NOT NULL,
	Pin VARCHAR(20) NOT NULL
)
GO 

CREATE TABLE BienThe(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_Laptop INT FOREIGN KEY REFERENCES Laptop(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	MaBienThe VARCHAR(20) UNIQUE NOT NULL,
	CPU INT FOREIGN KEY REFERENCES dbo.CPU(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	RAM INT FOREIGN KEY REFERENCES dbo.RAM(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	ManHinh INT FOREIGN KEY REFERENCES dbo.ManHinh(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	GPU INT FOREIGN KEY REFERENCES dbo.GPU(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	OCung INT FOREIGN KEY REFERENCES dbo.OCung(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	MauSac NVARCHAR(20) NOT NULL,
	HeDieuHanh INT FOREIGN KEY REFERENCES dbo.HeDieuHanh(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	Gia FLOAT NOT NULL,
	Hinh VARCHAR(255) NOT NULL
)
GO

CREATE TABLE Serial(
	ID int IDENTITY(1,1) PRIMARY KEY,
	ID_BienThe int FOREIGN KEY REFERENCES BienThe(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	SerialNumber VARCHAR(30) UNIQUE NOT NULL,
	TrangThai BIT NOT NULL
)
GO

CREATE TABLE NhaCungCap(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaNCC VARCHAR(20) UNIQUE NOT NULL,
	TenNCC NVARCHAR(100) NOT NULL,
	NguoiPhuTrach NVARCHAR(30) NOT NULL,
	SoDienThoai VARCHAR(13) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	DiaChi NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE HoaDonNhap(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaDN VARCHAR(30) UNIQUE NOT NULL,
	NhaCungCap INT FOREIGN KEY REFERENCES dbo.NhaCungCap(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	NgayTao DATE NOT NULL,
	TongTien FLOAT NOT NULL
)
GO

CREATE TABLE ChiTietHDN(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaDN INT FOREIGN KEY REFERENCES dbo.HoaDonNhap(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	ID_Serial INT FOREIGN KEY REFERENCES dbo.Serial(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
)
GO

CREATE TABLE DotGiamGia(
	MaDG VARCHAR(20) PRIMARY KEY,
	TenDG NVARCHAR(50) NOT NULL,
	Han DATE NOT NULL,
	GiaGiam FLOAT NOT NULL,
	DieuKienHoaDon FLOAT NOT NULL
)
GO

CREATE TABLE HinhThucVanChuyen(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HinhThuc NVARCHAR(30) NOT NULL,
	DonVi NVARCHAR(30) NOT NULL,
	GiaVC FLOAT NOT NULL
)
GO

CREATE TABLE HinhThucThanhToan(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HinhThuc NVARCHAR(30) NOT NULL
)
GO

CREATE TABLE HoaDon(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaHD VARCHAR(20) UNIQUE NOT NULL,
	MaKH VARCHAR(20) FOREIGN KEY REFERENCES dbo.KhachHang(MaKH) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	HinhThucVanChuyen INT FOREIGN KEY REFERENCES dbo.HinhThucVanChuyen(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	HinhThucThanhToan INT FOREIGN KEY REFERENCES dbo.HinhThucThanhToan(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	PhieuGiamGia INT FOREIGN KEY REFERENCES dbo.PhieuGiamGia(ID) ON DELETE CASCADE ON UPDATE CASCADE NULL,
	DotGiamGia VARCHAR(20) FOREIGN KEY REFERENCES dbo.DotGiamGia(MaDG) ON DELETE CASCADE ON UPDATE CASCADE NULL,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	NgayTao DATE NOT NULL,
	TongTien FLOAT NOT NULL
)
GO 
SELECT * FROM dbo.HoaDon
SELECT dbo.HoaDon.MaHD, HoaDon.MaKH,dbo.HinhThucVanChuyen.ID AS 'ID_HinhThucVanChuyen', dbo.HinhThucVanChuyen.HinhThuc AS 'HinhThucVanChuyen',dbo.HinhThucThanhToan.ID AS 'ID_HinhThucThanhToan',
	dbo.HinhThucThanhToan.HinhThuc AS 'HinhThucThanhToan',
	dbo.PhieuGiamGia.ID AS 'ID_PhieuGiamGia', PhieuGiamGia.MaPG, dbo.HoaDon.DotGiamGia,
	HoaDon.MaNV,
	dbo.HoaDon.NgayTao, dbo.HoaDon.TongTien
FROM dbo.HoaDon JOIN  dbo.KhachHang ON KhachHang.MaKH = HoaDon.MaKH
			JOIN dbo.HinhThucVanChuyen ON HinhThucVanChuyen.ID = HoaDon.HinhThucVanChuyen
			JOIN dbo.HinhThucThanhToan ON HinhThucThanhToan.ID = HoaDon.HinhThucThanhToan
			LEFT JOIN dbo.PhieuGiamGia ON PhieuGiamGia.ID = HoaDon.PhieuGiamGia
			LEFT JOIN dbo.DotGiamGia ON DotGiamGia.MaDG = dbo.HoaDon.DotGiamGia
			JOIN dbo.NhanVien ON NhanVien.MaNV = HoaDon.MaNV


CREATE TABLE CTHoaDon(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaHD INT FOREIGN KEY REFERENCES dbo.HoaDon(ID) ON UPDATE CASCADE NOT NULL,
	ID_Serial INT FOREIGN KEY REFERENCES dbo.Serial(ID) ON UPDATE CASCADE NOT NULL
)
GO 

SELECT dbo.HoaDon.ID AS 'ID_HoaDon', dbo.HoaDon.MaHD ,dbo.Serial.ID AS 'ID_Serial', dbo.Serial.SerialNumber 
FROM dbo.CTHoaDon JOIN dbo.HoaDon ON HoaDon.ID = CTHoaDon.MaHD
	JOIN dbo.Serial ON Serial.ID = CTHoaDon.ID_Serial

	SELECT * FROM dbo.CTHoaDon JOIN dbo.HoaDon ON HoaDon.ID = CTHoaDon.MaHD WHERE dbo.HoaDon.MaHD = 'HD001';

CREATE TABLE PhieuDoi(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaPhieuDoi VARCHAR(30) UNIQUE NOT NULL,
	MaKH VARCHAR(20) FOREIGN KEY REFERENCES dbo.KhachHang(MaKH) NOT NULL,
	MaHD INT FOREIGN KEY REFERENCES dbo.HoaDon(ID) NULL,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) NOT NULL,
	NgayTao DATE NOT NULL,
	LiDo NVARCHAR(255) NOT NULL
)
GO
SELECT * FROM dbo.HoaDon WHERE MaHD =?
CREATE TABLE CTPhieuDoi(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_PhieuDoi INT FOREIGN KEY REFERENCES dbo.PhieuDoi(ID) NOT NULL,
	ID_Serial_Old INT FOREIGN KEY REFERENCES dbo.Serial(ID) NOT NULL,
	ID_Serial_New INT FOREIGN KEY REFERENCES dbo.Serial(ID) NOT NULL
)
GO 
SELECT * FROM dbo.PhieuDoi WHERE MaPhieuDoi = ?
SELECT * FROM dbo.CTPhieuDoi JOIN dbo.PhieuDoi ON PhieuDoi.ID = CTPhieuDoi.ID_PhieuDoi WHERE MaPhieuDoi = 
SELECT * FROM dbo.PhieuDoi
SELECT * FROM dbo.CTPhieuDoi
DELETE FROM dbo.CTPhieuDoi WHERE ID_PhieuDoi = ?

SELECT dbo.PhieuDoi.ID AS 'ID_PhieuDoi', dbo.PhieuDoi.MaPhieuDoi,dbo.Serial.ID AS 'ID_Serial_Old', dbo.Serial.SerialNumber AS 'SerialNumber_Old', (SELECT Gia FROM dbo.BienThe JOIN dbo.Serial ON Serial.ID_BienThe = BienThe.ID JOIN dbo.CTPhieuDoi ON CTPhieuDoi.ID_Serial_Old = Serial.ID WHERE SerialNumber = dbo.CTPhieuDoi.ID_Serial_Old) AS [GiaCu],
	dbo.Serial.ID AS 'ID_Serial_New', dbo.Serial.SerialNumber AS 'SerialNumber_New'
FROM dbo.CTPhieuDoi JOIN dbo.PhieuDoi ON PhieuDoi.ID = CTPhieuDoi.ID_PhieuDoi
	JOIN dbo.Serial ON Serial.ID = CTPhieuDoi.ID_Serial_Old AND Serial.ID = CTPhieuDoi.ID_Serial_New
	JOIN dbo.BienThe ON BienThe.ID = Serial.ID_BienThe
GO


SELECT * FROM dbo.Serial
SELECT 
	dbo.CTPhieuDoi.ID,
    dbo.PhieuDoi.ID AS 'ID_PhieuDoi', 
    dbo.PhieuDoi.MaPhieuDoi,
    dbo.CTPhieuDoi.ID_Serial_Old AS 'ID_Serial_Old', 
    SerialOld.SerialNumber AS 'SerialNumber_Old',
	BienThe_Old.Gia AS 'Gia_Old',
    dbo.CTPhieuDoi.ID_Serial_New AS 'ID_Serial_New', 
    SerialNew.SerialNumber AS 'SerialNumber_New',
	BienThe_New.Gia AS 'Gia_New'
FROM  
    dbo.CTPhieuDoi 
JOIN 
    dbo.PhieuDoi ON PhieuDoi.ID = CTPhieuDoi.ID_PhieuDoi
JOIN 
    dbo.Serial AS SerialOld ON SerialOld.ID = CTPhieuDoi.ID_Serial_Old
JOIN 
    dbo.Serial AS SerialNew ON SerialNew.ID = CTPhieuDoi.ID_Serial_New
JOIN 
    dbo.BienThe AS BienThe_Old ON BienThe_Old.ID = SerialOld.ID_BienThe
JOIN 
	dbo.BienThe AS BienThe_New ON BienThe_New.ID = SerialNew.ID_BienThe
WHERE MaPhieuDoi = 'PD001'



	SELECT * FROM dbo.PhieuDoi
INSERT INTO dbo.PhieuDoi
(
    MaPhieuDoi,
    MaKH,
    MaHD,
    MaNV,
    NgayTao,
    LiDo
)
VALUES
(   'PD001',        -- MaPhieuDoi - varchar(30)
    'KH001',        -- MaKH - varchar(20)
    1,         -- MaHD - int
    'NV002',        -- MaNV - varchar(20)
    GETDATE(), -- NgayTao - date
    N'aa'        -- LiDo - nvarchar(255)
    )

INSERT INTO dbo.CTPhieuDoi
(
    ID_PhieuDoi,
    ID_Serial_Old,
    ID_Serial_New
)
VALUES
(   1, -- ID_PhieuDoi - int
    1, -- ID_Serial_Old - int
    2  -- ID_Serial_New - int
    )
CREATE TABLE LS_HoaDon(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) NOT NULL,
	MaHoaDon VARCHAR(20) FOREIGN KEY REFERENCES dbo.HoaDon(MaHD) NOT NULL,
	LichSuLamViec NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE LS_PhieuDoi(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaNV VARCHAR(20) FOREIGN KEY REFERENCES dbo.NhanVien(MaNV) NOT NULL,
	PhieuDoi INT FOREIGN KEY REFERENCES dbo.HoaDon(ID) NOT NULL,
	LichSuLamViec NVARCHAR(100) NOT NULL
)
GO

CREATE PROCEDURE InsertIntoBienThe
	@ID_Laptop INT,
	@MaBienThe VARCHAR(20),
	@CPU INT,
	@RAM INT,
	@ManHinh INT,
	@GPU INT,
	@OCung INT,
	@MauSac NVARCHAR(20),
	@HeDieuHanh INT,
	@Gia FLOAT,
	@Hinh VARCHAR(255)
AS
BEGIN
	IF NOT EXISTS (
		SELECT * FROM BienThe
		WHERE ID_Laptop = @ID_Laptop
		AND CPU = @CPU
		AND RAM = @RAM
		AND ManHinh = @ManHinh
		AND GPU = @GPU
		AND OCung = @OCung
		AND MauSac = @MauSac
		AND HeDieuHanh = @HeDieuHanh
	)
	BEGIN
		INSERT INTO BienThe(ID_Laptop, MaBienThe, CPU, RAM, ManHinh, GPU, OCung, MauSac, HeDieuHanh, Gia, Hinh)
		VALUES (@ID_Laptop, @MaBienThe, @CPU, @RAM, @ManHinh, @GPU, @OCung, @MauSac, @HeDieuHanh, @Gia, @Hinh)
	END
END
GO